# Site settings
title: Seth Gower
email: seth@sethgower.com
url: http://sethgower.com
description: "I am a computer engineering student at Rochester Institute of Technology, searching for a co-op in Software Engineering/Computer Engineering for the Summer of 2018"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Seth Gower

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/SethGower
  - title: facebook
    url: https://www.facebook.com/seth.gower.16
    
projects:
  - title: SUDS
    url: https://github.com/sethgower/suds
    description: A hackathon project I made to show the ocupancy status of the showers on floor. When the shower is locked, a limit switch is depressed which closes a circuit, illuminating an LED. Am planning on building a web app to show the status online. 
  - title: Resume
    url: https://github.com/sethgower/resume
    description: This is the LaTeX source code for my Resume. I wrote this template myself after reading other templates and learning from others
  - title: Pong
    url: https://github.com/sethgower/pong
    description: This is a 2 player recreation of the classic game Pong I made using Light Weight Java Game Library (LWJGL) which utilizes OpenGL

# Build settings
markdown: kramdown
permalink: pretty
