# Site settings
title: Seth Gower
email: sethzerish@gmail.com
url: http://sethgower.com
description: "I am a computer engineering student at Rochester Institute of Technology, searching for a co-op in Software Engineering/Computer Engineering for the Summer of 2018"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Seth Gower

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/seth.gower.16
  - title: github
    url: https://github.com/SethGower

# Build settings
markdown: kramdown
permalink: pretty
